module.exports = {
    language: "fr",
    fall: "Automne du",
    dawn: "Aube du",
    specific: "",
    hoursRemain: "heures hestantes",
    first: "Premier",
    second: "Deuxième",
    third: "Troisième",
    final: "Dernier",
    timeRemain: "Temps Restant",
    The: "",
    Day: "Jour",
    exit: "Sortir",
    minimize: "Minimiser",
    menu: "Menu",
    hours: " heures ",
    minutes: " minutes ",
    secondsRemain: " secondes restantes -",
    onNightOf: "Nuit du "
};