module.exports = {
    language: "de",
    fall: "Fall",
    dawn: "Dämmerung",
    specific: "Es Verbleiben ",
    hoursRemain: "Studen",
    first: "Ersten",
    second: "Zweiten",
    third: "Dritten",
    final: "Letzten",
    timeRemain: "Verbleibende Zeit",
    The: "Des",
    Day: "Tages",
    exit: "Ausgang",
    minimize: "Minimieren",
    menu: "Menü",
    hours: " Studen ",
    minutes: " Minuten ",
    secondsRemain: " Sekunden Bleiben -",
    onNightOf: "Nacht des "
};